version: '3.8'

services:
  split-bill-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=True
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add nginx for production deployment
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - split-bill-backend
    restart: unless-stopped
    profiles:
      - production

networks:
  default:
    name: split-bill-network